-- Baasha Fishing items for ESX (run on your database). Images: your inventory's image folder.
INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
  ('fish_anchovy', 'Anchovy', 1, 0, 1),
  ('fish_sardine', 'Sardine', 1, 0, 1),
  ('fish_mackerel', 'Mackerel', 1, 0, 1),
  ('fish_seabass', 'Sea Bass', 3, 0, 1),
  ('fish_snapper', 'Red Snapper', 3, 0, 1),
  ('fish_halibut', 'Halibut', 10, 0, 1),
  ('fish_stingray', 'Stingray', 9, 0, 1),
  ('fish_octopus', 'Octopus', 5, 0, 1),
  ('fish_moray', 'Moray Eel', 7, 0, 1),
  ('fish_bluegill', 'Bluegill', 1, 0, 1),
  ('fish_carp', 'Carp', 4, 0, 1),
  ('fish_catfish', 'Catfish', 8, 0, 1),
  ('fish_bass', 'Largemouth Bass', 3, 0, 1),
  ('fish_trout', 'Rainbow Trout', 2, 0, 1),
  ('fish_pike', 'Northern Pike', 6, 0, 1),
  ('fish_sturgeon', 'Sturgeon', 10, 0, 1),
  ('fish_goldcarp', 'Golden Carp', 6, 0, 1),
  ('fish_tuna', 'Bluefin Tuna', 10, 0, 1),
  ('fish_mahi', 'Mahi-Mahi', 10, 0, 1),
  ('fish_kingmackerel', 'King Mackerel', 6, 0, 1),
  ('fish_barracuda', 'Barracuda', 10, 0, 1),
  ('fish_swordfish', 'Swordfish', 10, 0, 1),
  ('fish_marlin', 'Blue Marlin', 10, 0, 1),
  ('fish_hammerhead', 'Hammerhead Shark', 10, 0, 1),
  ('fish_greatwhite', 'Great White Shark', 10, 0, 1),
  ('junk_boot', 'Old Boot', 1, 0, 1),
  ('junk_can', 'Rusty Tin Can', 1, 0, 1),
  ('junk_tire', 'Bike Tire', 1, 0, 1);
