-- Baasha Fishing items for ox_inventory (ox_inventory/data/items.lua) — paste inside return { ... }
-- Copy install/images/*.png into ox_inventory/web/images/
    ['fish_anchovy'] = { label = 'Anchovy', weight = 100, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_sardine'] = { label = 'Sardine', weight = 200, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_mackerel'] = { label = 'Mackerel', weight = 750, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_seabass'] = { label = 'Sea Bass', weight = 3000, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_snapper'] = { label = 'Red Snapper', weight = 3500, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_halibut'] = { label = 'Halibut', weight = 10000, stack = true, close = false, description = 'Rare fish. Sell it at the fish market or cook it.' },
    ['fish_stingray'] = { label = 'Stingray', weight = 9000, stack = true, close = false, description = 'Rare fish. Sell it at the fish market or cook it.' },
    ['fish_octopus'] = { label = 'Octopus', weight = 5500, stack = true, close = false, description = 'Epic fish. Sell it at the fish market or cook it.' },
    ['fish_moray'] = { label = 'Moray Eel', weight = 7000, stack = true, close = false, description = 'Epic fish. Sell it at the fish market or cook it.' },
    ['fish_bluegill'] = { label = 'Bluegill', weight = 300, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_carp'] = { label = 'Carp', weight = 4500, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_catfish'] = { label = 'Catfish', weight = 8500, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_bass'] = { label = 'Largemouth Bass', weight = 3000, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_trout'] = { label = 'Rainbow Trout', weight = 2500, stack = true, close = false, description = 'Rare fish. Sell it at the fish market or cook it.' },
    ['fish_pike'] = { label = 'Northern Pike', weight = 6000, stack = true, close = false, description = 'Rare fish. Sell it at the fish market or cook it.' },
    ['fish_sturgeon'] = { label = 'Sturgeon', weight = 10000, stack = true, close = false, description = 'Epic fish. Sell it at the fish market or cook it.' },
    ['fish_goldcarp'] = { label = 'Golden Carp', weight = 6500, stack = true, close = false, description = 'Legendary fish. Sell it at the fish market or cook it.' },
    ['fish_tuna'] = { label = 'Bluefin Tuna', weight = 10000, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_mahi'] = { label = 'Mahi-Mahi', weight = 10000, stack = true, close = false, description = 'Uncommon fish. Sell it at the fish market or cook it.' },
    ['fish_kingmackerel'] = { label = 'King Mackerel', weight = 6000, stack = true, close = false, description = 'Common fish. Sell it at the fish market or cook it.' },
    ['fish_barracuda'] = { label = 'Barracuda', weight = 10000, stack = true, close = false, description = 'Rare fish. Sell it at the fish market or cook it.' },
    ['fish_swordfish'] = { label = 'Swordfish', weight = 10000, stack = true, close = false, description = 'Epic fish. Sell it at the fish market or cook it.' },
    ['fish_marlin'] = { label = 'Blue Marlin', weight = 10000, stack = true, close = false, description = 'Epic fish. Sell it at the fish market or cook it.' },
    ['fish_hammerhead'] = { label = 'Hammerhead Shark', weight = 10000, stack = true, close = false, description = 'Legendary fish. Sell it at the fish market or cook it.' },
    ['fish_greatwhite'] = { label = 'Great White Shark', weight = 10000, stack = true, close = false, description = 'Legendary fish. Sell it at the fish market or cook it.' },
    ['junk_boot'] = { label = 'Old Boot', weight = 500, stack = true, close = false, description = 'Junk fished out of the water. Worth a dollar or two at the fish market.' },
    ['junk_can'] = { label = 'Rusty Tin Can', weight = 500, stack = true, close = false, description = 'Junk fished out of the water. Worth a dollar or two at the fish market.' },
    ['junk_tire'] = { label = 'Bike Tire', weight = 500, stack = true, close = false, description = 'Junk fished out of the water. Worth a dollar or two at the fish market.' },
